services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - dev.env
    ports:
      - "5432:${POSTGRES_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  minio:
    image: bitnami/minio:latest
    restart: always
    env_file:
      - dev.env
    volumes:
      - minio-data:/bitnami/minio/data

volumes:
  postgres-data:
    driver: local
  minio-data:
    driver: local