services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - front.dev.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  minio:
    image: bitnami/minio:latest
    restart: always
    env_file:
      - front.dev.env
    volumes:
      - minio-data:/bitnami/minio/data

  es:
    image: bitnami/elasticsearch:latest
    restart: always
    env_file:
      - front.dev.env
    volumes:
      - es-data:/usr/share/elasticsearch/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - front.dev.env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
      - minio

volumes:
  postgres-data:
    driver: local
  minio-data:
    driver: local
  es-data:
    driver: local
