services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - DATABASE_SYNCHRONIZE=${DATABASE_SYNCHRONIZE}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
      - ELASTICSEARCH_NODES=${ELASTICSEARCH_NODES}
      - MINIO_API_PORT_NUMBER=${MINIO_API_PORT_NUMBER}
      - MINIO_CONSOLE_PORT_NUMBER=${MINIO_CONSOLE_PORT_NUMBER}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_DEFAULT_BUCKETS=${MINIO_DEFAULT_BUCKETS}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_SERVER_URL=${MINIO_SERVER_URL}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      es:
        condition: service_healthy

  postgres:
    image: postgres:17.5
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  minio:
    image: bitnami/minio:2025.5.24-debian-12-r7
    restart: always
    environment:
      - MINIO_API_PORT_NUMBER=${MINIO_API_PORT_NUMBER}
      - MINIO_CONSOLE_PORT_NUMBER=${MINIO_CONSOLE_PORT_NUMBER}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_DEFAULT_BUCKETS=${MINIO_DEFAULT_BUCKETS}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_SERVER_URL=${MINIO_SERVER_URL}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    volumes:
      - minio-data:/bitnami/minio/data
    healthcheck:
      test: ["CMD-SHELL", "mc alias set local http://localhost:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD} >/dev/null 2>&1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  es:
    image: bitnami/bitnami/elasticsearch:9.0.2-debian-12-r1
    restart: always
    depends_on:
      - postgres
    volumes:
      - es-data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:9200/_cluster/health || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  postgres-data:
    driver: local
  minio-data:
    driver: local
  es-data:
    driver: local
