services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - dev.env
    ports:
      - "5432:${POSTGRES_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  minio:
    image: bitnami/minio:latest
    restart: always
    env_file:
      - dev.env
    environment:
      - MINIO_API_PORT_NUMBER=${MINIO_PORT}
      - MINIO_CONSOLE_PORT_NUMBER=9001
      - MINIO_DEFAULT_BUCKETS=${MINIO_BUCKET_NAME}
    ports:
      - "${MINIO_PORT}:${MINIO_PORT}"
      - "9001:9001"
    volumes:
      - minio-data:/bitnami/minio/data

  meilisearch:
    image: getmeili/meilisearch:v1.9
    restart: always
    env_file:
      - dev.env
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - MEILI_HTTP_ADDR=0.0.0.0:${MEILI_PORT}
      - MEILI_ENV=${MEILI_ENV}
    ports:
      - "${MEILI_PORT}:${MEILI_PORT}"
    volumes:
      - meilisearch-data:/meili_data

  redis:
    image: redis:7-alpine
    restart: always
    env_file:
      - dev.env
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

volumes:
  postgres-data:
    driver: local
  minio-data:
    driver: local
  meilisearch-data:
    driver: local
  redis-data:
    driver: local