services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - front.dev.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  minio:
    image: bitnami/minio:latest
    restart: always
    env_file:
      - front.dev.env
    environment:
      - MINIO_API_PORT_NUMBER=${MINIO_PORT}
      - MINIO_CONSOLE_PORT_NUMBER=9001
      - MINIO_DEFAULT_BUCKETS=${MINIO_BUCKET_NAME}
    ports:
      - "${MINIO_PORT}:${MINIO_PORT}"
      - "9001:9001"
    volumes:
      - minio-data:/bitnami/minio/data
    healthcheck:
      test: ["CMD-SHELL", "mc alias set local http://localhost:${MINIO_PORT} $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD} >/dev/null 2>&1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  meilisearch:
    image: getmeili/meilisearch:v1.9
    restart: always
    env_file:
      - front.dev.env
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - MEILI_HTTP_ADDR=0.0.0.0:7700
      - MEILI_ENV=${MEILI_ENV}
    ports:
      - "7700:7700"
    volumes:
      - meilisearch-data:/meili_data
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:7700/health || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    restart: always
    env_file:
      - front.dev.env
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - front.dev.env
    ports:
      - "${PORT}:${PORT}"
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:${PORT}/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      meilisearch:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres-data:
    driver: local
  minio-data:
    driver: local
  meilisearch-data:
    driver: local
  redis-data:
    driver: local
